EWPP-768: Adds Description List field type.
openeuropa/description_list_field pull request #1
Opened 2021-02-17 21:01 UTC by 22Alexandra

2021-02-19 11:10 UTC, sergepavle commented on templates/description-list.html.twig
> +      <dd>{{ item.description }}</dd>
We may also not to output an empty dt/dd tags if the values are empty.
But it is an optional comment.

2021-02-19 11:10 UTC, sergepavle commented on tests/src/Functional/DescriptionListFieldWidgetTest.php
> +    $this->assertEquals($expected_values, $node->get('description_list')->first()->getValue());
It would be good to add tests with 'Add another item' for testing multiple fields.

2021-02-22 11:01 UTC, sergepavle submitted a review, later dismissed

2021-02-24 11:01 UTC, sergepavle submitted a review, later dismissed

2021-02-24 13:30 UTC, upchuk requested changes
Let's use percona 5.7 like everywhere else

2021-02-24 13:30 UTC, upchuk commented on src/Plugin/Field/FieldType/DescriptionListFieldItem.php
> +          'type' => 'varchar_ascii',
Why ascii? Didn't we run into trouble with this elsewhere? Let's use varchar

2021-02-24 13:30 UTC, upchuk commented on src/Plugin/Field/FieldType/DescriptionListFieldItem.php
> +  public function applyDefaultValue($notify = TRUE) {
Do we need this?

2021-02-24 13:30 UTC, upchuk commented on src/Plugin/Field/FieldWidget/DescriptionListFieldWidget.php
> +      return $sub_element;
Do we have subelements here? Why is this needed? Also, if really needed, let's add a comment here describing a bit this rather cryptic logic.

2021-02-24 13:30 UTC, upchuk commented on templates/description-list.html.twig
> +        <dt>{{ item.term }}</dt>
This doesn't really work. I left one term empty and it printed the <dt>:

<img width="306" alt="Screen Shot 2021-02-24 at 14 26 20" src="https://user-images.githubusercontent.com/5848933/109007305-493b2f00-76ac-11eb-8142-9322d6dd4a6a.png">

It means it's missing also some test coverage.

2021-02-24 14:23 UTC, upchuk submitted a review, later dismissed

2021-02-24 14:27 UTC, sergepavle commented on templates/description-list.html.twig
> +      {% if item.term['#plain_text'] is not empty %}
```suggestion
      {% if item.term['#plain_text'] %}
```

2021-02-24 14:27 UTC, sergepavle commented on templates/description-list.html.twig
> +      {% if item.description['#text'] is not empty %}
```suggestion
      {% if item.description['#text'] %}
```

2021-02-24 15:04 UTC, upchuk approved these changes

2021-02-24 15:04 UTC, sergepavle approved these changes

2021-02-24 15:04 UTC, merged